### ISSUE TITLE
Unable to use Eureka plugin with Hazelcast 3.11

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast-eureka#21]
If Hazelcast Eureka plugin 1.0.2 is placed on a classpath together with Hazelcast 3.11, Hazelcast member fails to start.

**Exception:**
```
Exception in thread "main" java.lang.IllegalArgumentException: DataSerializableFactory[-45] is already registered! com.hazelcast.journal.EventJournalDataSerializerHook$1@702657cc -> com.hazelcast.internal.journal.EventJournalDataSerializerHook$1@6a6cb05c
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.register(DataSerializableSerializer.java:91)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.<init>(DataSerializableSerializer.java:70)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:96)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1$Builder.build(SerializationServiceV1.java:313)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:299)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:237)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:208)
	at com.hazelcast.instance.Node.<init>(Node.java:217)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:156)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:202)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:181)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at cz.cacek.test.App.main(App.java:13)
```

**Test application**
```java
import com.hazelcast.core.Hazelcast;
import com.hazelcast.instance.HazelcastInstanceFactory;

public class App {
    public static void main(String[] args) {
        try {
            Hazelcast.newHazelcastInstance();
        } finally {
            HazelcastInstanceFactory.terminateAll();
        }
    }
}
```

**Maven dependencies**
```xml
    <dependencies>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-all</artifactId>
            <version>3.11</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-eureka-one</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

[test-app-eureka-reproducer.zip](https://github.com/hazelcast/hazelcast-eureka/files/2576803/test-app-eureka-reproducer.zip)

**Comment by googlielmo** [comment]
You're right @kwart, the Eureka plugin pulls in a dependency on hazelcast 3.9.3.
This is wrong. As a workaround in your `pom.xml` you have to specify an exclusion for it
```
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-eureka-one</artifactId>
            <version>1.0.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.hazelcast</groupId>
                    <artifactId>hazelcast</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by kwart** [comment]
@leszko Your suggested solution sounds as the correct one. :)
