### ISSUE TITLE
Hazelcast server with Eureka discovery 

### ISSUE THREAD

**Issue by vladaurosh** [hazelcast/hazelcast-eureka#48]
Hello.
I am trying to use eureka discovery with hazelcast-3.12.6 but having issues with it.
I've followed instructions on this url
[https://github.com/hazelcast/hazelcast-eureka/blob/master/README.md](https://github.com/hazelcast/hazelcast-eureka/blob/master/README.md)
added hazelcast-eureka-one into classpath, but I am getting this error when I start hazelcast node using start.sh:
```
INFO: [192.168.1.195]:5701 [prod] [3.12.6] Hazelcast 3.12.6 (20200130 - be02cc5) starting at [192.168.1.195]:5701
Apr 12, 2020 4:28:32 PM com.hazelcast.system
INFO: [192.168.1.195]:5701 [prod] [3.12.6] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
Apr 12, 2020 4:28:33 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [192.168.1.195]:5701 [prod] [3.12.6] Backpressure is disabled
Apr 12, 2020 4:28:33 PM com.hazelcast.instance.Node
INFO: [192.168.1.195]:5701 [prod] [3.12.6] Shutting down connection manager...
Apr 12, 2020 4:28:33 PM com.hazelcast.instance.Node
INFO: [192.168.1.195]:5701 [prod] [3.12.6] Shutting down node engine...
Apr 12, 2020 4:28:33 PM com.hazelcast.instance.NodeExtension
INFO: [192.168.1.195]:5701 [prod] [3.12.6] Destroying node NodeExtension.
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Lists
        at com.hazelcast.eureka.one.EurekaOneDiscoveryStrategyFactory.<clinit>(EurekaOneDiscoveryStrategyFactory.java:37)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.hazelcast.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:291)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.collectFactories(DefaultDiscoveryService.java:163)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:137)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:57)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
        at com.hazelcast.instance.Node.createDiscoveryService(Node.java:318)
        at com.hazelcast.instance.Node.<init>(Node.java:255)
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:161)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:229)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:208)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:158)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.StartServer.main(StartServer.java:46)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 19 more
```
Everything works fine if I use mutlicast or tcp discovery.

This is what I have in hazelcast.xml:
```
<eureka enabled="true">
                <self-registration>true</self-registration>
                <namespace>hazelcast</namespace>
                <use-classpath-eureka-client-props>false</use-classpath-eureka-client-props>
                <shouldUseDns>false</shouldUseDns>
                <name>hazelcast-test</name>
                <serviceUrl.default>http://user:pass@registry:8761/eureka</serviceUrl.default>
</eureka>
```

Any help would be appreciated.

**Comment by vladaurosh** [comment]
I managed to make this work by adding following jars in classpath:
animal-sniffer-annotations-1.18.jar
annotations-3.0.1.jar
antlr-runtime-3.5.2.jar
aopalliance-1.0.jar
archaius-core-0.7.7.jar
commons-codec-1.14.jar
commons-configuration-1.10.jar
commons-lang-2.6.jar
commons-logging-1.2.jar
commons-math3-3.6.1.jar
error_prone_annotations-2.3.4.jar
eureka-client-1.9.20.jar
gson-2.8.6.jar
guava-28.2-jre.jar
guice-4.2.3.jar
hazelcast-eureka-one-1.1.2.jar
httpclient-4.5.12.jar
httpcore-4.4.13.jar
j2objc-annotations-1.3.jar
jackson-annotations-2.10.3.jar
jackson-core-2.10.3.jar
jackson-databind-2.10.3.jar
javax.inject-1.jar
javax.servlet-api-4.0.1.jar
jersey-apache-client4-1.19.4.jar
jersey-client-1.19.4.jar
jersey-core-1.19.4.jar
jettison-1.4.1.jar
joda-time-2.10.5.jar
jsr305-3.0.2.jar
jsr311-api-1.1.1.jar
netflix-eventbus-0.3.0.jar
netflix-infix-0.3.0.jar
servo-core-0.12.28.jar
servo-internal-0.10.1.jar
slf4j-api-1.7.30.jar
spectator-api-0.105.0.jar
stax-api-1.0-2.jar
stringtemplate-4.0.2.jar
xmlpull-1.1.3.1.jar
xpp3-1.1.6.jar
xstream-1.4.11.1.jar
