### ISSUE TITLE
Remove compactmap dependency

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-eureka#52]
Follow this https://github.com/Netflix/eureka/pull/1235 to remove the dependency on `compactmap`.

We need to get rid of this dependency, because of the source code audit (it's LGPL license):
```
sources/hazelcast-docker/rt/hazelcast_hazelcast-jet-enterprise_4analysis.tar/opt/hazelcast-jet-enterprise/lib/compactmap-1.2.1.jar
sources/hazelcast-docker/rt/hazelcast_hazelcast-enterprise_4analysis.tar/opt/hazelcast/lib/compactmap-1.2.1.jar
sources/hazelcast-docker/rt/hazelcast_hazelcast-jet_4analysis.tar/opt/hazelcast-jet/lib/compactmap-1.2.1.jar
sources/docker_images/hazelcast_hazelcast-jet_4analysis.tar/opt/hazelcast-jet/lib/compactmap-1.2.1.jar
sources/docker_images/hazelcast_hazelcast_4analysis.tar/opt/hazelcast/lib/compactmap-1.2.1.jar
sources/hazelcast-docker/rt/hazelcast_hazelcast_4analysis.tar/opt/hazelcast/lib/compactmap-1.2.1.jar
sources/docker_images/hazelcast_hazelcast-jet-enterprise_4analysis.tar/opt/hazelcast-jet-enterprise/lib/compactmap-1.2.1.jar
sources/docker_images/hazelcast_hazelcast-enterprise_4analysis.tar/opt/hazelcast/lib/compactmap-1.2.1.jar
```

**Comment by jerrinot** [comment]
perhaps we can just upgrade the compactmap library? as newer version are licensed as Apache 2.0

**Comment by leszko** [comment]
FYI: I checked and simply removing the compactmap dependency doesn't work, because when using Hazelcast Eureka plugin, it throws the following exception. I'll check if upgrading `compactmap` to `2.0` helps. And if this doesn't work, then I'll dig into the issue.

```
javax.ws.rs.WebApplicationException: null
        at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:107) ~[eureka-client-1.9.3.jar!/:1.9.3]
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:198) ~[eureka-client-1.9.3.jar!/
:1.9.3]
        at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:165) ~[eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118) ~[eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79) ~[eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1473) [eureka-client-1.9.3.jar!/:1.9.3]
        at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1440) [eureka-client-1.9.3.jar!/:1.9.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

**Comment by leszko** [comment]
Updating CompactMap to `2.0` looks fine though. Sent a PR: #53
